### ISSUE TITLE
Use Craft form macros for consistent styling

### ISSUE THREAD

**Issue by thijskaspers** [davist11/craft-listing-section#2]
Hi @davist11,

Why don't you use the default Craft selectfield styling? Timkelty has sent you a pull-request for this, which will use the "_includes/forms/select" macro.

Greetings

**Comment by davist11** [comment]
Hah probably because the custom select wasn't around when the plugin was first released. I'll merge that pull request in soon, but honestly, this plugin is kind of defunct, and https://github.com/lewisjenkins/craft-lj-dynamicfields is much more powerful.

**Comment by thijskaspers** [comment]
Ah thanks! ;) Didn't know that plugin yet, but it sure comes in handy.
