### ISSUE TITLE
Craft 3 support

### ISSUE THREAD

**Issue by jamesmacwhite** [davist11/craft-listing-section#4]
Hi @davist11 

My organisation currently uses this plugin in a Craft 2 project. Currently I am going through the Craft 3 migration process and identifying plugins that need support in Craft 3. While this plugin has a potential Craft 3 alternative (Craft Dynamic Fields), I like the simplicity of this field type and therefore maybe would still want to use it in Craft 3.

I don't know if you had any plans for Craft 3 support for this plugin given the last activity was in 2014, but I'd be willing to port it to Craft 3 potentially if this is not going to happen.

Thanks!

**Comment by davist11** [comment]
Because of dynamic fields, I didn't have plans to upgrade it any time soon. But, if you want to submit a PR with the upgrade, it would certainly likely speed up the process.
